name: Deploy NuGet Package
description: Deploy NuGet Package to NuGet URL
author: Lee Lott

inputs:
  nuget-file-path:
    description: 'The full path to the NuGet package to deploy'
    required: true
  nuget-url:
    description: 'The URL to the GitHub NuGet packages'
    required: true
  nuget-package-name:
    description: 'The name of the NuGet package to use for this release'
    required: true
  nuget-package-version:
    description: 'The version number of the NuGet package to use for this release.'
    required: true    
  token:
    description: 'The GitHub token used for authentication to upload the NuGet package'
    required: true

runs:
  using: "composite"
  steps:
    - name: Create Release
      shell: pwsh
      run: dotnet nuget push ${{ inputs.nuget-file-path }} --api-key ${{ inputs.token }} --source ${{ inputs.nuget-url }} --skip-duplicate        

    - name: Add to Job Summary
      shell: pwsh
      run: |
        "# NuGet Package Deployment Summary" | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8
        "Published NuGet package **${{ inputs.nuget-package-name }}.${{ inputs.nuget-package-version }}** to NuGet URL **${{ inputs.nuget-url }}**." | Out-File -FilePath $env:GITHUB_STEP_SUMMARY -Append -Encoding utf8